version: '3'

services:
  node-apps:
    # image: sample-node-app
    build: .
    restart: always
    ports:
      - ${PORTS}
      # 3000 port on our local machine will be mapped to port 5500 in container
    depends_on:
      - mongo_services
    # env_file:
    #     - .env 
    environment:
      - MONGO_LINK=mongodb://sample_mongo:27017/sample_db
      

  mongo_services:
    container_name: sample_mongo
    image: mongo:latest
    # volumes:
    #   - ./data:/data/db
    ports:
      - '2717:27017'
    restart: always