version: '3'

services:
  node-app:
    image: sample-node-app
    build: .
    restart: always
    ports:
      - ${PORTS}
      # 3000 port on our local machine will be mapped to port 5500 in container
    external_links:
      - mongo
    env_file:
        - .env 

  mongo_service:
    container_name: sample_mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27012:27017'